package Generic_utilities;

import java.io.File;
import java.io.IOException;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.testng.ITestListener;
import org.testng.ITestResult;

public class Listeners implements ITestListener{     // here say when we have to get some properties from class to interface we use "implements" and class to class is"extends".
                                                   //Next step is to take teh cursor to the next line basically enter and do rightclick on your mouse,click source- overrideimplemented methods-on testfailure -ok.
	
	public void onTestFailure(ITestResult result) // tehn delete teh line @override then delete teh line // todoautogenerated.tehn delete the line - ITestListener.super.onTestFailure(result);
	{
		TakesScreenshot ts = (TakesScreenshot)BaseClass.sdriver;     // Now here start typing(takescreenshot).so basically we have to downcast the "driver". And driver is found in base class. so open teh base classnow. and do the changes like reintilizing another driver called sdriver.
		                                       // then call Baseclass method and also call .sdriver.Then you store it in avariable called "ts".
		// Now take the variable down,call getscreenshot method,call the other methods too,tehn save it in the varaible"src"
		// after this we have to save the screen shot in a destination called
	
		
		File src = ts.getScreenshotAs(OutputType.FILE);
		File dest = new File("./failedScript.png");  // here first you type exactly "./failedScript.png",tehn  type newFile  and call it tehn save inside the bracket.tehn sav eteh entire thing in a variable dest".
	                                                // so here we directly cannot save it hence we have to call FileUtil method and the call .copyFile(src,dest)
		                                           // here it will show an error click that,tehn delet teh //todoautogeentated line.
		
		try {
			FileUtils.copyFile(src, dest);
		} catch (IOException e) {
		
			e.printStackTrace();
		} 
		
	}                                       // after following all the above steps we need to implement it hence open create camp file.
	// so what we will do is since teh original script has passed teh asertion ,hence we have to intensionally fail the assertion  as follows
	// so we will open crete camp file and implement to it ,so in create camp class we will type Listenersanotation,teh inside teh bracket we have to give the package name.listeners followed by class name and tehn .class we have to mention lets see how
	// @listeners(Generic_utilities.Listeners.class) above the classname.
	// rest of teh steps are in create campfile.
	
	
	

}
